name: publish
on: [push]
jobs:
  publish-connector-lastfm-influx-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the connector-lastfm-influx Docker image
        run: |
          docker build . --tag ghcr.io/johntdyer/connector-lastfm-influx:latest
          docker run ghcr.io/johntdyer/connector-lastfm-influx:latest
          docker push ghcr.io/johntdyer/connector-lastfm-influx:latest